build: false
shallow_clone: true

cache:
  - .\php -> appveyor.yml
  - vendor -> composer.lock

init:
  - set PATH=%PATH%;.\php
  - set COMPOSER_NO_INTERACTION=1
  - set CACHED=0

install:
  - if exist .\php (set CACHED=1) else (mkdir .\php)
  - if %CACHED%==0 cd .\php
  - if %CACHED%==0 curl -fsS -o php.zip https://windows.php.net/downloads/releases/archives/php-7.2.0-Win32-VC15-x64.zip
  - if %CACHED%==0 appveyor DownloadFile https://getcomposer.org/composer.phar
  - if %CACHED%==0 7z x php.zip -y
  - if %CACHED%==0 copy php.ini-production php.ini /Y
  - if %CACHED%==0 echo date.timezone="Europe/Berlin" >> php.ini
  - if %CACHED%==0 echo extension_dir=ext >> php.ini
  - if %CACHED%==0 echo extension=php_openssl.dll >> php.ini
  - if %CACHED%==0 echo extension=php_mbstring.dll >> php.ini
  - if %CACHED%==0 echo zend.assertions = 1 >> php.ini
  - if %CACHED%==0 cd ..

test_script:
  - php .\php\composer.phar install
  - vendor/bin/phpunit.bat --coverage-text
